target.adjudicate.service.url=https://solis-adj-dataservice-809287589165.northamerica-northeast1.run.app/publish
target.adjudicate.service.retry.url=https://solis-adj-dataservice-809287589165.northamerica-northeast1.run.app/retryAdjResponse
target.totals.service.url=https://solis-adj-dataservice-809287589165.northamerica-northeast1.run.app/totals
target.dis.bc.hl7.event.url=https://solis-dis-dataservice-809287589165.northamerica-northeast1.run.app/api/dis/bc/publish
