server.port=9090

spring.config.import=sm://

target.adjudicate.service.url=${ADJUDICATE_SERVICE_URL:http://localhost:8080/publish}
target.adjudicate.service.retry.url=${ADJUDICATE_RETRY_SERVICE_URL:http://localhost:8080/retryAdjResponse}
target.totals.service.url=${TOTALS_SERVICE_URL:http://localhost:8080/totals}
target.dis.bc.hl7.event.url=${DIS_BC_HL7_EVENT_URL:http://localhost:8080/api/dis/bc/publish}
target.dis.nl.hl7.event.url=${DIS_NL_HL7_EVENT_URL:http://localhost:8080/api/dis/nl/publish}

gateway.api-key=${sm://solis-dis-gateway-api-key}
