# Load Balancer base URL
gateway.base-url=http://${GATEWAY_HOST:34.98.75.115}

target.adjudicate.service.url=${gateway.base-url}/publish
target.adjudicate.service.retry.url=${gateway.base-url}/retryAdjResponse
target.totals.service.url=${gateway.base-url}/totals
target.dis.bc.hl7.event.url=${gateway.base-url}/api/dis/bc/publish
target.dis.nl.hl7.event.url=${gateway.base-url}/api/dis/nl/publish

# API key from Secret Manager
gateway.api-key=${sm://solis-dis-gateway-api-key}
